src/Entity/Domain.php
<?php

namespace App\Entity;

use App\Repository\DomainRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DomainRepository::class)
 */
class Domain
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $domain_name;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDomainName(): ?string
    {
        return $this->domain_name;
    }

    public function setDomainName(string $domain_name): self
    {
        $this->domain_name = $domain_name;

        return $this;
    }



}

src/Entity/TranslationKey.php
<?php

namespace App\Entity;

use App\Repository\TranslationKeyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * @ORM\Entity(repositoryClass=TranslationKeyRepository::class)
 *
 */
class TranslationKey
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $text_key;

    /**
     * @ORM\OneToMany(targetEntity=TranslationMessage::class, mappedBy="translation_key", orphanRemoval=true)
     */
    private $translationMessages;


    /**
     * @ORM\ManyToMany(targetEntity=Domain::class)
     * @ORM\JoinTable(name="domain_translation_key", joinColumns={@ORM\JoinColumn(name="domain_id", referencedColumnName="id")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="translation_key_id", referencedColumnName="id")})
     */
     private $domains;



    /**
     * TranslationKey constructor.
     */
    public function __construct()
    {
        $this->translationMessages = new ArrayCollection();
        $this->domains = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getTextKey(): ?string
    {
        return $this->text_key;
    }

    /**
     * @param string $text_key
     * @return $this
     */
    public function setTextKey(string $text_key): self
    {
        $this->text_key = $text_key;

        return $this;
    }

    /**
     * @return Collection|TranslationMessage[]
     */
    public function getTranslationMessages(): Collection
    {
        return $this->translationMessages;
    }

    /**
     * @param TranslationMessage $translationMessage
     * @return $this
     */
    public function addTranslationMessage(TranslationMessage $translationMessage): self
    {
        if (!$this->translationMessages->contains($translationMessage)) {
            $this->translationMessages[] = $translationMessage;
            $translationMessage->setTranslationKey($this);
        }

        return $this;
    }

    /**
     * @param TranslationMessage $translationMessage
     * @return $this
     */
    public function removeTranslationMessage(TranslationMessage $translationMessage): self
    {
        if ($this->translationMessages->contains($translationMessage)) {
            $this->translationMessages->removeElement($translationMessage);
            // set the owning side to null (unless already changed)
            if ($translationMessage->getTranslationKey() === $this) {
                $translationMessage->setTranslationKey(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Domain[]
     */
    public function getDomains(): Collection
    {
        return $this->domains;
    }

    public function addDomain(Domain $domain): self
    {
        if (!$this->domains->contains($domain)) {
            $this->domains[] = $domain;
            $domain->addTranslationKey($this);
        }

        return $this;
    }

    public function removeDomain(Domain $domain): self
    {
        if ($this->domains->contains($domain)) {
            $this->domains->removeElement($domain);
            $domain->removeTranslationKey($this);
        }

        return $this;
    }

}

src/Controller/KeyController.php
<?php

namespace App\Controller;

use App\Entity\Domain;
use App\Entity\TranslationKey;
use App\Entity\TranslationMessage;
use App\Form\MessageType;
use App\Service\CsvFileToArray;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;


class KeyController extends AbstractController
{

    /**
     *
     * @Route("/view/{id_key}", name="view_key")
     * @param int $id_key
     * @return Response
     */
    public function showDetails(int $id_key)
    {

        //Find the selected key
        $key_entry = $this->getDoctrine()
            ->getRepository('App:TranslationKey')
            ->find($id_key);

        $data['formdata'] = $key_entry;

        return $this->render('key/view.html.twig', $data);
    }

    /**
     *
     * @Route("/modify/{translation_key}", name="modify_key")
     * @param Request $request
     * @param TranslationKey $translation_key
     * @return RedirectResponse|Response
     */
    public function modifyEntry(Request $request, TranslationKey $translation_key)
    {
        $data = [];
        $data['mode'] = 'modify';
        $form = $this->createFormBuilder($translation_key)
            ->add('text_key')
            ->add(
                'translationmessages',
                CollectionType::class,
                ['entry_type' => MessageType::class,
                  'allow_add' => true,
                   ]
            )
            ->add(
                'domains',
                EntityType::class,
                ['class' => Domain::class,
                    'label' => 'domain_name',
                    'choice_label' => function ($item) {
                        return $item->getDomainName();
                    },
                    'mapped'=>true,
                    'expanded' => true,
                    'multiple'=>true,
                    'allow_extra_fields'=>true]

            )
            ->add('submit',
                SubmitType::class
            )
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $entitymanager = $this->getDoctrine()->getManager();
            $entitymanager->persist($translation_key);
            $entitymanager->flush();
            return $this->redirectToRoute('index_keys');
        } else {
            $data['formdata'] = $form->createView();
        }

        return $this->render('key/form.html.twig', $data);
    }

    /**
     *
     * @Route("/new", name="new_key")
     * @param Request $request
     * @return RedirectResponse|Response
     */
    public function addEntry(Request $request)
    {
        $data['formdata'] = [];
        $data['mode'] = 'new';

        $translation_key = new TranslationKey;
        $translation_message_nl = new TranslationMessage;
        $translation_message_en = new TranslationMessage;

        $translation_message_nl->setLanguage('nl');
        $translation_message_nl->setMessage("");
        $translation_message_en->setLanguage('en');
        $translation_message_en->setMessage("");
        $translation_key->addTranslationMessage($translation_message_nl);
        $translation_key->addTranslationMessage($translation_message_en);

        $form = $this->createFormBuilder($translation_key)
            ->add('text_key')
            ->add(
                'translationmessages',
                CollectionType::class,
                [
                    'entry_type' => MessageType::class,
                    'allow_add' => true,
                    ]
            )
            ->add(
                'domains',
                EntityType::class,
                ['class' => Domain::class,
                    'label' => 'domain_name',
                    'choice_label' => function ($item) {
                        return $item->getDomainName();
                    },
                    'mapped'=>true,
                    'expanded' => true,
                    'multiple'=>true,
                    'allow_extra_fields'=>true]

            )
            ->add('submit', SubmitType::class)
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $entitymanager = $this->getDoctrine()->getManager();
            $entitymanager->persist($translation_key);
            $entitymanager->persist($translation_message_en);
            $entitymanager->persist($translation_message_nl);
            $entitymanager->flush();

            return $this->redirectToRoute('index_keys');
        } else {
            $data['formdata'] = $form->createView();
        }
        return $this->render('key/form.html.twig', $data);
    }

    /**
     *
     * @Route("/delete/{translation_key}", name="delete_key")
     * @param Request $request
     * @param TranslationKey $translation_key
     * @return Response
     */
    public function deleteKey(Request $request, TranslationKey $translation_key)
    {
        $form = $this->createFormBuilder($translation_key)
            ->add('text_key')
            ->add(
                'translationmessages',
                CollectionType::class,
                array(
                    'entry_type' => MessageType::class,
                    'allow_add' => true,
                )
            )
            ->add('submit', SubmitType::class)
            ->getForm();

        $form->handleRequest($request);


        if ($form->isSubmitted()) {
            $entitymanager = $this->getDoctrine()->getManager();
            $entitymanager->remove($translation_key);
            $entitymanager->flush();
            return $this->redirectToRoute('index_keys');
        } else {
            $data['formdata'] = $form->createView();
        }
        return $this->render('key/delete.html.twig', $data);
    }





}

templates/key/delete.html.twig
{% extends "key/index.html.twig" %}
{% block title %}Delete{% endblock title %}
{% block content %}
<header>
    <h1 class="delete">Confirm Delete Key</h1>
</header>
<main>
    {{ form_start(formdata) }}
    <div>
        {{ form_errors(formdata) }}
    </div>
    <div>
        <div>
           <h4>Do you want to delete the Key <span class="color_blue">{{ formdata.text_key.vars.value }} </span> and its messages?</h4>
        </div>
        <h4>Messages</h4>
        {% for message in formdata.translationmessages %}
            <p>
                <strong>{{message.language.vars.value}}</strong>
                {{message.message.vars.value}}</p>

        {% endfor %}
        <div class="display_none">
            {{ form_row(formdata.text_key) }}
            {{ form_row(formdata.translationmessages) }}
        </div>
        <div>
            {{ form_row(formdata.submit) }}
        </div>
    </div>
    {{ form_end(formdata) }}

        <a class="a_link"href="{{path("index_keys")}}"><button>Back</button></a>

</main>
{% endblock content %}

templates/key/download.html.twig
{% extends "key/index.html.twig" %}
{% block title %}Download{% endblock title %}
{% block content %}
    <header>
        <h1>Download the 2 Translation message files </h1>

    </header>
    <main>
        <div class="form_container">
            {{ form_start(formdata) }}
            <div>
                {{ form_errors(formdata) }}
            </div>

            <div class="upload_form">
                <div>{{ form_row(formdata.chose_file) }}</div>
                <div>
                    {{ form_row(formdata.download) }}
                </div>
            </div>
            {{ form_end(formdata) }}

        </div>


        <div>
            <a class="a_link" href="{{path("index_keys")}}"><button>Back</button></a>
        </div>
    </main>
{% endblock content %}

templates/key/form.html.twig
{% extends "key/index.html.twig" %}
{% block title %}Edit or Add{% endblock title %}
{% block content %}
		<header>
			<h1>{{mode == 'new' ? 'Add New Key' : 'Modify Key'}}</h1>
		</header>
		<main>
			{{ form_start(formdata) }}
			<div>
				{{ form_errors(formdata) }}
			</div>

			<div class="form_container">
				<div>
					{{ form_label(formdata.text_key, 'Translation Key') }}
					{{ form_widget(formdata.text_key) }}
				</div>

				<div>
					{% for translationmessage in formdata.translationmessages %}
						<p>
							{{form_label(translationmessage.message, translationmessage.language.vars.value)}}
							{{ form_widget(translationmessage.message) }}</p>
					{% endfor %}
				</div>
				<div>
					{{ form_row(formdata.domains) }}
				</div>
				<div>
					{{ form_row(formdata.submit) }}
				</div>
			</div>
			{%  do formdata.translationmessages.setRendered %}
			{{ form_end(formdata) }}
			<div>
				<a class="a_link"href="{{path("index_keys")}}"><button>Back</button></a>
			</div>
		</main>
{% endblock content %}

templates/key/index.html.twig
{% extends "./base.html.twig" %}
{% block title %}Translator{% endblock title %}
{% block content %}
		<header>
			<h1>Keys</h1>
			<h4>
				User can view, add, update, search or delete a key in the Translator Keys
			</h4>
		</header>
		<main>
			<a class="action" href="{{path("new_key")}}">Create a new key</a>
			<div class="search-form">
				{{ form_start(formdata) }}
				<div>
					{{ form_errors(formdata) }}
				</div>
				<p>{{ form_row(formdata.search_value) }}</p>
				<p>{{ form_row(formdata.filter_domain) }}</p>
				<p>{{ form_row(formdata.empty_keys) }}</p>
				<p>
					{{ form_row(formdata.search) }}</p>
				{{ form_end(formdata) }}
			</div>
			<div>
				<a class="a_link"href="{{path("index_domains")}}"><button class="button-primary">Domains</button></a>
				<a class="a_link"href="{{path("file_handle")}}"><button class="button-primary">Upload/Download</button></a>
			</div>
			<div class="keys_table">
				{% if translation_keys is not empty %}
					<table id="keys" class="list">
						<thead>
						<tr>
							<th>ID</th>
							<th>Text</th>
							<th>NL</th>
							<th>Last Updated</th>
							<th>EN</th>
							<th>Last Updated</th>
							<th>&nbsp;</th>
							<th>&nbsp;</th>
							<th>&nbsp;</th>
						</tr>
						</thead>
						<tbody>
						{%  for entry in translation_keys %}
							<tr>
								<td>{{entry.id}}</td>
								<td>{{entry.textKey}}</td>
								{% for message in entry.translationMessages %}
									{% if message.language == 'nl'%}
										<td>{{message.message|slice(0,15)|raw}}
											{% if message.message|length > 15 %}
												...
											{% endif %}
										</td>
										<td>{% if message.updated is not empty %}{{ message.updated|date('Y-m-d H:i:s', "Europe/Paris")  }}{% endif %}</td>
									{% endif %}
								{% endfor %}
								{% for message in entry.translationMessages %}
									{% if message.language == 'en'%}
										<td>{{message.message|slice(0,15)|raw}}
											{% if message.message|length > 15 %}
												...
											{% endif %}
										</td>
										<td>{% if message.updated is not empty %}{{ message.updated|date('Y-m-d H:i:s', "Europe/Paris")  }}{% endif %}</td>
									{% endif %}
								{% endfor %}

								<td>
									<a class="action" href="{{path("view_key", {'id_key': entry.id})}}">View</a>
								</td>
								<td>
									<a class="action" href="{{path("modify_key", {'translation_key': entry.id})}}">Edit</a>
								</td>
								<td>
									<a class="action" href="{{path("delete_key", {'translation_key': entry.id})}}">Delete</a>
								</td>
							</tr>
						{% endfor %}
						</tbody>

					</table>
				{% endif %}
			</div>
			{% if translation_keys is empty %}
				<p>No Entry Found!!</p>
			{% endif %}

		</main>
{%  endblock content %}

templates/key/upload.html.twig
{% extends "key/index.html.twig" %}
{% block title %}Translator{% endblock title %}
{% block content %}
    <header>
        <h1>Upload or Download Translation message files here...</h1>

    </header>
    <main>
        <div class="form_container">
            {{ form_start(uploadForm) }}
             <div>
                {{ form_errors(uploadForm) }}
            </div>

            <div class="upload_form">
                <div>{{ form_row(uploadForm.nl_file) }}</div>
                <div>{{ form_row(uploadForm.en_file) }}</div>
                <div>
                    {{ form_row(uploadForm.upload) }}
                </div>
            </div>
            {{ form_end(uploadForm) }}

        </div>
        <div>
            <ul>
                <li> <p>All Keys in NL</p><a class="a_link"href="{{path("download_file", {'filter': 'nl'})}}"><button>Download</button></a></li>
                <li> <p>All Keys in EN</p><a class="a_link"href="{{path("download_file",  {'filter': 'en'})}}"><button>Download</button></a></li>
                {% for domain in domains %}
                <li><p>All {{ domain.domainName }} Keys in NL</p> <a class="a_link"href="{{path("download_file",  {'filter': domain.domainName~'_nl'})}}"><button>Download</button></a></li>
                <li> <p>All {{ domain.domainName }} Keys in EN</p><a class="a_link"href="{{path("download_file",  {'filter': domain.domainName~'_en'})}}"><button>Download</button></a></li>
                {% endfor %}
            </ul>

        </div>

        <div>
            <a class="a_link"href="{{path("index_keys")}}"><button>Back</button></a>
        </div>
    </main>
{% endblock content %}

templates/key/view.html.twig
{% extends "key/index.html.twig" %}
{% block title %}View details{% endblock title %}
{% block content %}
		<header>
			<h1>View Key Details</h1>
		</header>
		<main>
			<h4>Text</h4>
			<p>
				{{formdata.textKey}}</p>
			<h4>Messages</h4>

			{% for message in formdata.translationMessages %}

				<p>
					<strong>{{message.language}}</strong>
					{{message.message}}</p>
			{% endfor %}

			<h4>Domains</h4>
			{% for domain in formdata.domains %}
				<p>
					<strong>{{domain.domainName}}</strong></p>

			{% endfor %}
					<a class="a_link"href="{{path("index_keys")}}"><button>Back</button></a>
		</main>
		{% endblock content %}